// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using catering_back.Servicios;

namespace catering_back.Migrations
{
    [DbContext(typeof(CateringDbContext))]
    partial class CateringDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("catering_back.Modelos.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre_ingrediente");

                    b.HasKey("Id");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("catering_back.Modelos.Ingrediente_menu", b =>
                {
                    b.Property<int>("Id_menu");

                    b.Property<int>("Id_ingrediente");

                    b.HasKey("Id_menu", "Id_ingrediente");

                    b.HasIndex("Id_ingrediente");

                    b.ToTable("Ingredientes_menus");
                });

            modelBuilder.Entity("catering_back.Modelos.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Foto");

                    b.Property<int>("Id_reserva");

                    b.Property<int>("Id_tipo_menu");

                    b.Property<string>("Ingredientes_menu");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("Id_reserva");

                    b.HasIndex("Id_tipo_menu");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("catering_back.Modelos.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Estado")
                        .IsRequired();

                    b.Property<string>("Id_menu")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("catering_back.Modelos.Tipo_menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tipo")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Tipos_menus");
                });

            modelBuilder.Entity("catering_back.Modelos.Ingrediente_menu", b =>
                {
                    b.HasOne("catering_back.Modelos.Ingrediente", "Ingrediente")
                        .WithMany("Ingredientes_Menus")
                        .HasForeignKey("Id_ingrediente")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("catering_back.Modelos.Menu", "Menu")
                        .WithMany("Ingredientes_Menus")
                        .HasForeignKey("Id_menu")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("catering_back.Modelos.Menu", b =>
                {
                    b.HasOne("catering_back.Modelos.Reserva", "Reserva")
                        .WithMany("Menus")
                        .HasForeignKey("Id_reserva")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("catering_back.Modelos.Tipo_menu", "Tipo_menu")
                        .WithMany("Menus")
                        .HasForeignKey("Id_tipo_menu")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
